apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project-management-agents.fullname" . }}-env
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
